export default {
    products: [{
        _id: 1,
        image: '/images/candy.jpg',
        categorie: '1kg',
        name: '"THANK YOU" 8-PIECE',
        description: 'Qui non in proident labore dolor elit adipisicing irure tempor amet do.',
        price: 20.90,
        countInStock: 0,
    },
    {
        _id: 2,
        image: '/images/candy.jpg',
        categorie: '500g',
        name: '"THANK YOU" 3-PIECE',
        description: 'Qui non in proident labore dolor elit adipisicing irure tempor amet do.',
        price: 12.90,
        countInStock: 6,
    },
    {
        _id: 3,
        image: '/images/candy.jpg',
        categorie: '1kg',
        name: '"XOXO" 8-PIECE CANDY',
        description: 'Qui non in proident labore dolor elit adipisicing irure tempor amet do.',
        price: 10,
        countInStock: 6,
    },
    {
        _id: 4,
        image: '/images/candy.jpg',
        categorie: '500g',
        name: '"XOXO" 3-PIECE CANDY',
        description: 'Qui non in proident labore dolor elit adipisicing irure tempor amet do.',
        price: 12.90,
        countInStock: 6,
    },
    {
        _id: 5,
        image: '/images/candy.jpg',
        categorie: '1kg',
        name: '"CONGRATS" 8-PIECE',
        description: 'Qui non in proident labore dolor elit adipisicing irure tempor amet do.',
        price: 12.90,
        countInStock: 6,
    },
    {
        _id: 6,
        image: '/images/candy.jpg',
        categorie: '500g',
        name: '"CONGRATS" 3-PIECE',
        description: 'Qui non in proident labore dolor elit adipisicing irure tempor amet do.',
        price: 12.90,
        countInStock: 6,
    },
    {
        _id: 7,
        image: '/images/candy.jpg',
        categorie: '1kg',
        name: 'SIGNATURE 8-PIECE CANDY',
        description: 'Qui non in proident labore dolor elit adipisicing irure tempor amet do.',
        price: 12.90,
        countInStock: 6,
    },
    {
        _id: 8,
        image: '/images/candy.jpg',
        categorie: '500g',
        name: 'SIGNATURE 3-PIECE CANDY',
        description: 'Qui non in proident labore dolor elit adipisicing irure tempor amet do.',
        price: 12.90,
        countInStock: 6,
    }]
}
